---
title: "Plotting Results"
author: "Gleison M. Azevedo"
format: html
editor: visual
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  results = FALSE
)
```

## Import libraries

```{r libs}
library(ggplot2)
library(ggraph)
library(dplyr)
library(tidyr)
library(igraph)
library(purrr)
library(vroom)
library(paletteer)
library(easylayout)
library(UpSetR)
```

## Define Functions

```{r funcs}
# Set colors
color_mappings <- c("#06141FFF", "#742C14FF", "#3D4F7DFF", 
                    "#E48C2AFF", "#72874EFF", "#046E8FFF")
```

## Load Data

```{r data}
merged_paths <- vroom::vroom("results/orthology_data/merged_paths.csv")
df <- vroom::vroom("results/metastasis_genes/metastasis_genes.csv")
nodelist <- vroom::vroom("results/orthology_data/nodelist.csv ")
network_filtered <- vroom::vroom("results/orthology_data/network_filtered.csv")
source_statements <- colnames(nodelist)[10:length(nodelist)]
```

## Plotting Intersections

```{r plots}
upset(dplyr::select(as.data.frame(nodelist), 
                    "queryItem", 
                    "cell adhesion",                          
                    "extracellular matrix organization",      
                    "epithelial to mesenchymal transition",   
                    "regulation of metallopeptidase activity",
                    "cell junction organization",             
                    "cellular extravasation"),
                    nsets = 50, nintersects = NA,
      sets.bar.color = color_mappings, 
      mainbar.y.label = "Intersecção dos \nProcessos Biológicos",
      sets.x.label = "Tamanho do set")
```

## Graph Build

```{r graph}
graph <-
  graph_from_data_frame(network_filtered, directed = FALSE, vertices = nodelist)

layout <- easylayout::vivagraph(graph)
layout <- easylayout::vivagraph(graph, layout = layout, pin_nodes = TRUE, lcc_margin_left = 10)
V(graph)$x <- layout[, 1]
V(graph)$y <- layout[, 2]

#save(graph, file = "results/plots/graph")
```




```{r plots}
ggraph(graph, "manual", x = V(graph)$x, y = V(graph)$y) +
  geom_edge_link0(color = "#90909020") +
  geom_node_point(aes(color = -root), size = 1.5) +
  coord_fixed() +
  theme_void() +
  theme(legend.position = "bottom")
```


```{r plots}
ggraph::ggraph(graph,
               "manual",
               x = V(graph)$x,
               y = V(graph)$y) +
  ggraph:: geom_edge_link0(edge_width = 0.5, color = "#90909020") +
  scatterpie::geom_scatterpie(
    cols = source_statements,
    data = igraph::as_data_frame(graph, "vertices"),
    colour = NA,
    pie_scale = 0.40
  ) +
  geom_node_text(aes(label = nodelist$queryItem, colour = "red"), nudge_x = 0.8, nudge_y = 0.8, size = 2) +
  ggplot2::scale_fill_manual(values = color_mappings, drop = FALSE)

ggraph::ggraph(graph,
               "manual",
               x = V(graph)$x,
               y = V(graph)$y) +
  ggraph:: geom_edge_link0(edge_width = 0.5, color = "#90909020") +
  scatterpie::geom_scatterpie(
    cols = source_statements,
    data = igraph::as_data_frame(graph, "vertices"),
    colour = NA,
    pie_scale = 0.40
  ) +
  ggplot2::scale_fill_manual(values = color_mappings, drop = FALSE)
```